[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50
maxMessageSize = 100
enableWebsocketCompression = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4F8BF9"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"
